### ISSUE TITLE
The WFA default dar file populates the password field as string while it should be password

### ISSUE THREAD

**Issue by aviadoffer** [Itaiweisman/IBOX_NetApp_WFA#1]
The test will work but inside a workflow it will not since the password will always be sent as the encrypted password instead of the real one.
Attached a corrected dat.
[Infinidat_WFA_Create_Volume.zip](https://github.com/Itaiweisman/IBOX_NetApp_WFA/files/2700151/Infinidat_WFA_Create_Volume.zip)

**Comment by Itaiweisman** [comment]
Thanks Aviad.

**Comment by Itaiweisman** [comment]
replaced the dar file with an updated one
